export type Glyph = | 'cross'
					| 'info'
					| 'shot'
					| 'clock'
					| 'hit'
					| 'accuracy'
					| 'play'
					| 'full_screen'
					| 'ability'
					| 'left'
					| 'repeat'
					| 'flag'
					;